---
- name: Add GOPATH in zshrc
  lineinfile:
    path: "$HOME/.zshrc"
    line: "export GOPATH=$HOME/go"
    state: present

- name: Update PATH with GOPATH in zshrc
  lineinfile:
    path: "$HOME/.zshrc"
    line: 'export PATH="${GOPATH}/bin:${PATH}"'
    state: present
